### PR TITLE
fix parsing port and path (#1072)

### PR DESCRIPTION
**Pull request by eyaroslavtsev**
Ref
https://github.com/TheWeatherCompany/grid-api/issues/1072

### CODE REVIEW

**Comment by eyaroslavtsev** [comment]
hey @clstokes urgent PR is ready

**Comment by eyaroslavtsev** [comment]
hi @TheWeatherCompany/grid-admin can you review it? thanks

**Comment by ckelner** [comment]
@eyaroslavtsev is this using dasein code style?  Some of it looks off to me.  As far as what the issue was, can you explain where the error was and how the new code avoids it please?

**Comment by eyaroslavtsev** [comment]
hey @ckelner i've fix code style. It was a long time ago, i will try to remember

**Comment by eyaroslavtsev** [comment]
hey @ckelner 
As in documentation http://docs.aws.amazon.com/ElasticLoadBalancing/latest/APIReference/API_HealthCheck.html
we should parse _targets_ (without _protocol_ as `HTTP` and etc) like as:
1.`80/weather/us/wa/seattle`
2.`80/weather/`
3.`80/weather`
4...

but earlier method works only for 3 variant
[here](https://github.com/TheWeatherCompany/dasein-cloud-aws/blob/develop/src/main/java/org/dasein/cloud/aws/network/ElasticLoadBalancer.java#L1394-1394) and [here](https://github.com/TheWeatherCompany/dasein-cloud-aws/blob/develop/src/main/java/org/dasein/cloud/aws/network/ElasticLoadBalancer.java#L1389-1389) we got NumberFormatException in other cases

New code separate `80/weather/us/wa/seattle` to port=`80` and path=`/weather/us/wa/seattle` if incoming string have `/`

**Comment by ckelner** [comment]
Very good.  Thank you.
I'll merge this once Jekins is clear.

**Pull request merged**
