### PR TITLE
fix removing a tag from an instance with bad region (#997)

### PR DESCRIPTION
**Pull request by eyaroslavtsev**
Ref
https://github.com/TheWeatherCompany/grid-api/pull/1015

### CODE REVIEW

**Comment by ckelner** [comment]
Hey @eyaroslavtsev could you please merge in the latest from develop please.  Thanks.

**Comment by ckelner** [comment]
@eyaroslavtsev let's also create a new method for this operation.  We can call it `removeTagsWithVerification` or something like that.  This way we do not impact existing Dasein consumers.

**Comment by ckelner** [comment]
Hey @eyaroslavtsev are any of these changes needed then?

**Comment by ckelner** [comment]
@eyaroslavtsev are there changes here we actually need for TheWeatherCompany/grid-api#1015 ?

**Comment by eyaroslavtsev** [comment]
@ckelner i think this changes not need for us

**Comment by ckelner** [comment]
Ok.  Closing.

**Pull request closed without merging**
