### PR TITLE
Issue 702 More informative error message for dependencies when deleting a network

### PR DESCRIPTION
**Pull request by mgulimonov**
Ref https://github.com/TheWeatherCompany/grid-api/issues/702

### CODE REVIEW

**Comment by ckelner** [comment]
@clstokes if you have time please

**Comment by clstokes** [comment]
Hey @mgulimonov, can you help my understand the intent of these changes? Based on the initial issue, this seems like a lot of changes to support it.

**Comment by mgulimonov** [comment]
Hey @clstokes 
The intent of these changes is to remove unneccesary duplication in AWS method invocation.  EC2Method invocation is moved to new class - EC2Gateway. Also EC2Filter class was introduced to simplify adding parameters to EC2Method. It's not necessary to use this concept everywhere, but creation the new methods for AWS provider can be significantly simplified.

See for example this code snippet:

``` java
EC2Filter filter = EC2Filter.singleParameterFilter("RouteTableId", routingTableId);
getEc2Gateway().invoke(ELBMethod.DELETE_ROUTE_TABLE, filter);
```

**Comment by ckelner** [comment]
Hey @mgulimonov can we use https://github.com/TheWeatherCompany/dasein-cloud-core/blob/develop/src/main/java/org/dasein/cloud/compute/VMFilterOptions.java instead?  We think it makes sense to re-use this existing class rather than create a new one?  Is it possible to add subnets for filtering to it?

**Comment by ckelner** [comment]
Ref: https://github.com/TheWeatherCompany/dasein-cloud-core/pull/68

**Comment by mgulimonov** [comment]
VmFilterOptions is used as transfer object between applications layers, and contains information related to virtual machines only. Ec2filter should be used to supply parameters to ec2method and is used only in aws layer. So it's just a different concept.

**Comment by mgulimonov** [comment]
If you want to replace vmfilter with VmFilterOptions - I'll take a look.

**Comment by ckelner** [comment]
@mgulimonov I will discuss with @clstokes again today.

**Comment by mgulimonov** [comment]
Hey, @ckelner 
Could you please take another look at this PR?

**Comment by ckelner** [comment]
Changed assignment to @ckelner

**Pull request merged**
